FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

ENV PYTHONPATH=/app

COPY .env .env

CMD ["python", "app/service/consumers/explosive_content_consumer.py"]