FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

COPY .env .env

ENV PYTHONPATH=/app

CMD ["python", "app/service/consumers/user_quote_consumer.py"]